# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resamp_cpp <- function(x, boot, seed) {
    .Call(`_soildiv_resamp_cpp`, x, boot, seed)
}

